# Generated by Django 5.0.2 on 2024-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='heading1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='heading2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='heading3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='heading4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='heading5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='heading6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='para1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='para6',
            field=models.TextField(blank=True),
        ),
    ]
